Document: redak
Title: Debian redak Manual
Author: <insert document author here>
Abstract: This manual describes what redak is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/redak/redak.sgml.gz

Format: postscript
Files: /usr/share/doc/redak/redak.ps.gz

Format: text
Files: /usr/share/doc/redak/redak.text.gz

Format: HTML
Index: /usr/share/doc/redak/html/index.html
Files: /usr/share/doc/redak/html/*.html
